# Generated by Django 2.2.6 on 2020-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='b_group',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
