# Generated by Django 2.2.6 on 2020-01-19 14:57

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.ForeignKey, to='hospital.Test'),
        ),
    ]
