# Generated by Django 2.2.6 on 2020-01-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20200119_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='test',
            new_name='t',
        ),
    ]
