# Generated by Django 2.2.6 on 2020-01-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20200119_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='t',
        ),
        migrations.AddField(
            model_name='testing',
            name='test',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
