# Generated by Django 2.2.6 on 2020-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_auto_20200119_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='o_days',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='o_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
