# Generated by Django 2.2.6 on 2020-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20200119_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cnic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='purpose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
