# Generated by Django 2.2.6 on 2020-01-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='m_name',
        ),
    ]
